# Generated by Django 5.0 on 2025-09-26 03:24

import caching.base
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("orders", "0004_expressorder_scheduledorder_standardorder_and_more"),
        ("payments", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="SSLCommerzPayment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "payment_type",
                    models.CharField(
                        choices=[
                            ("sslcommerz", "SSLCommerz Payment"),
                            ("stripe", "Stripe Payment"),
                            ("paypal", "PayPal Payment"),
                        ],
                        default="sslcommerz",
                        max_length=20,
                    ),
                ),
                ("transaction_id", models.CharField(max_length=100, unique=True)),
                ("amount", models.DecimalField(decimal_places=2, max_digits=10)),
                ("currency", models.CharField(default="BDT", max_length=3)),
                (
                    "_status",
                    models.CharField(
                        db_column="status",
                        default="pending",
                        max_length=20,
                    ),
                ),
                ("session_key", models.CharField(blank=True, max_length=200)),
                ("gateway_response", models.JSONField(blank=True, default=dict)),
                ("validation_response", models.JSONField(blank=True, default=dict)),
                ("val_id", models.CharField(blank=True, max_length=100)),
                ("bank_tran_id", models.CharField(blank=True, max_length=100)),
                ("card_type", models.CharField(blank=True, max_length=50)),
                ("card_no", models.CharField(blank=True, max_length=20)),
            ],
            options={
                "db_table": "payments_sslcommerzpayment",
            },
            bases=(caching.base.CachingMixin, models.Model),
        ),
        migrations.CreateModel(
            name="StripePayment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "payment_type",
                    models.CharField(
                        choices=[
                            ("sslcommerz", "SSLCommerz Payment"),
                            ("stripe", "Stripe Payment"),
                            ("paypal", "PayPal Payment"),
                        ],
                        default="sslcommerz",
                        max_length=20,
                    ),
                ),
                ("transaction_id", models.CharField(max_length=100, unique=True)),
                ("amount", models.DecimalField(decimal_places=2, max_digits=10)),
                ("currency", models.CharField(default="BDT", max_length=3)),
                (
                    "_status",
                    models.CharField(
                        db_column="status",
                        default="pending",
                        max_length=20,
                    ),
                ),
                (
                    "stripe_payment_intent_id",
                    models.CharField(blank=True, max_length=100),
                ),
                ("client_secret", models.CharField(blank=True, max_length=200)),
                ("gateway_response", models.JSONField(blank=True, default=dict)),
            ],
            options={
                "db_table": "payments_stripepayment",
            },
            bases=(caching.base.CachingMixin, models.Model),
        ),
        migrations.RemoveField(
            model_name="payment",
            name="status",
        ),
        migrations.AddField(
            model_name="payment",
            name="_status",
            field=models.CharField(
                choices=[
                    ("pending", "Pending"),
                    ("processing", "Processing"),
                    ("completed", "Completed"),
                    ("failed", "Failed"),
                    ("cancelled", "Cancelled"),
                    ("refunded", "Refunded"),
                    ("disputed", "Disputed"),
                ],
                db_column="status",
                db_index=True,
                default="pending",
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="payment",
            name="amount",
            field=models.DecimalField(db_index=True, decimal_places=2, max_digits=10),
        ),
        migrations.AlterField(
            model_name="payment",
            name="transaction_id",
            field=models.CharField(db_index=True, max_length=100, unique=True),
        ),
        migrations.AddIndex(
            model_name="payment",
            index=models.Index(
                fields=["_status"],
                name="payments_pa_status_7ad4af_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="payment",
            index=models.Index(
                fields=["created_at"],
                name="payments_pa_created_b8a300_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="payment",
            index=models.Index(
                fields=["_status", "created_at"],
                name="payments_pa_status_343680_idx",
            ),
        ),
        migrations.AddField(
            model_name="sslcommerzpayment",
            name="order",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="%(class)s_payment",
                to="orders.order",
            ),
        ),
        migrations.AddField(
            model_name="stripepayment",
            name="order",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="%(class)s_payment",
                to="orders.order",
            ),
        ),
    ]
