# Generated by Django 5.0 on 2025-09-26 11:38

import django.utils.timezone
import model_utils.fields
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("orders", "0005_remove_order_orders_orde_status_25e057_idx_and_more"),
        ("payments", "0002_sslcommerzpayment_stripepayment_and_more"),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name="payment",
            name="payments_pa_created_b8a300_idx",
        ),
        migrations.RemoveIndex(
            model_name="payment",
            name="payments_pa_status_343680_idx",
        ),
        migrations.RemoveField(
            model_name="payment",
            name="created_at",
        ),
        migrations.RemoveField(
            model_name="payment",
            name="updated_at",
        ),
        migrations.RemoveField(
            model_name="sslcommerzpayment",
            name="created_at",
        ),
        migrations.RemoveField(
            model_name="sslcommerzpayment",
            name="updated_at",
        ),
        migrations.RemoveField(
            model_name="stripepayment",
            name="created_at",
        ),
        migrations.RemoveField(
            model_name="stripepayment",
            name="updated_at",
        ),
        migrations.AddField(
            model_name="payment",
            name="created",
            field=model_utils.fields.AutoCreatedField(
                default=django.utils.timezone.now,
                editable=False,
                verbose_name="created",
            ),
        ),
        migrations.AddField(
            model_name="payment",
            name="modified",
            field=model_utils.fields.AutoLastModifiedField(
                default=django.utils.timezone.now,
                editable=False,
                verbose_name="modified",
            ),
        ),
        migrations.AddField(
            model_name="sslcommerzpayment",
            name="created",
            field=model_utils.fields.AutoCreatedField(
                default=django.utils.timezone.now,
                editable=False,
                verbose_name="created",
            ),
        ),
        migrations.AddField(
            model_name="sslcommerzpayment",
            name="modified",
            field=model_utils.fields.AutoLastModifiedField(
                default=django.utils.timezone.now,
                editable=False,
                verbose_name="modified",
            ),
        ),
        migrations.AddField(
            model_name="stripepayment",
            name="created",
            field=model_utils.fields.AutoCreatedField(
                default=django.utils.timezone.now,
                editable=False,
                verbose_name="created",
            ),
        ),
        migrations.AddField(
            model_name="stripepayment",
            name="modified",
            field=model_utils.fields.AutoLastModifiedField(
                default=django.utils.timezone.now,
                editable=False,
                verbose_name="modified",
            ),
        ),
        migrations.AddIndex(
            model_name="payment",
            index=models.Index(
                fields=["created"],
                name="payments_pa_created_708743_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="payment",
            index=models.Index(
                fields=["_status", "created"],
                name="payments_pa_status_540537_idx",
            ),
        ),
    ]
