# Generated by Django 5.0 on 2025-09-27 19:22

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("payments", "0003_remove_payment_payments_pa_created_b8a300_idx_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="stripepayment",
            name="order",
        ),
        migrations.DeleteModel(
            name="SSLCommerzPayment",
        ),
        migrations.DeleteModel(
            name="StripePayment",
        ),
    ]
