[project]
name = "homeser-backend"
version = "0.0.1"
requires-python = ">=3.10"
dependencies = [
    "asgiref==3.9.1",
    "astroid==2.3.3",
    "attrs==25.3.0",
    "certifi==2019.11.28",
    "chardet==3.0.4",
    "charset-normalizer==3.4.3",
    "cloudinary==1.44.1",
    "dj-database-url==2.1.0",
    "django==5.0",
    "django-cloudinary-storage==0.3.0",
    "django-cors-headers==4.3.1",
    "django-environ==0.11.2",
    "django-redis==6.0.0",
    "djangorestframework==3.14.0",
    "djangorestframework-simplejwt==5.3.0",
    "drf-spectacular==0.27.2",
    "gunicorn==21.2.0",
    "idna==2.8",
    "inflection==0.5.1",
    "isort==4.3.21",
    "jsonschema==4.25.1",
    "jsonschema-specifications==2025.9.1",
    "lazy-object-proxy==1.4.3",
    "mccabe==0.6.1",
    "packaging==25.0",
    "pillow==11.3.0",
    "psycopg2-binary==2.9.10",
    "pyjwt==2.10.1",
    "python-decouple>=3.8",
    "pytz==2025.2",
    "pyyaml==6.0.2",
    "redis==6.4.0",
    "referencing==0.36.2",
    "requests==2.32.3",
    "rpds-py==0.27.1",
    "ruff==0.12.12",
    "setuptools==80.9.0",
    "six==1.17.0",
    "sqlparse==0.5.3",
    "sslcommerz-python-api==1.0.1",
    "typing-extensions==4.15.0",
    "tzdata==2025.2",
    "uritemplate==4.2.0",
    "urllib3==2.3.0",
    "whitenoise==6.6.0",
    "wrapt==1.11.2",
]

[tool.uv]
package = false
