# Generated by Django 5.2.7 on 2025-10-23 10:06


import cloudinary.models
import django.core.validators
import django.db.models.deletion
import django.utils.timezone
import django_lifecycle.mixins
import model_utils.fields
from django.conf import settings
from django.db import migrations, models

import services.models
import services.validators
import utils.validation_utils


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="ServiceCategory",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created",
                    model_utils.fields.AutoCreatedField(
                        default=django.utils.timezone.now,
                        editable=False,
                        verbose_name="created",
                    ),
                ),
                (
                    "modified",
                    model_utils.fields.AutoLastModifiedField(
                        default=django.utils.timezone.now,
                        editable=False,
                        verbose_name="modified",
                    ),
                ),
                ("name", models.CharField(db_index=True, max_length=200)),
                ("slug", models.SlugField(blank=True, unique=True)),
                ("description", models.TextField(blank=True)),
                (
                    "icon",
                    cloudinary.models.CloudinaryField(
                        blank=True, max_length=255, null=True, verbose_name="image"
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "Service Categories",
            },
        ),
        migrations.CreateModel(
            name="Service",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created",
                    model_utils.fields.AutoCreatedField(
                        default=django.utils.timezone.now,
                        editable=False,
                        verbose_name="created",
                    ),
                ),
                (
                    "modified",
                    model_utils.fields.AutoLastModifiedField(
                        default=django.utils.timezone.now,
                        editable=False,
                        verbose_name="modified",
                    ),
                ),
                ("name", models.CharField(db_index=True, max_length=200)),
                ("slug", models.SlugField(blank=True, unique=True)),
                (
                    "short_desc",
                    models.CharField(
                        db_index=True,
                        max_length=300,
                        validators=[services.models.validate_service_short_desc],
                    ),
                ),
                (
                    "description",
                    models.TextField(
                        validators=[services.models.validate_service_description]
                    ),
                ),
                (
                    "price",
                    models.DecimalField(
                        db_index=True,
                        decimal_places=2,
                        max_digits=10,
                        validators=[utils.validation_utils.validate_positive_price],
                    ),
                ),
                (
                    "image",
                    models.ImageField(
                        blank=True,
                        null=True,
                        upload_to="services/",
                        validators=[
                            services.validators.validate_image_file_extension,
                            services.validators.validate_image_file_size,
                            services.validators.validate_image_aspect_ratio,
                        ],
                    ),
                ),
                ("is_active", models.BooleanField(db_index=True, default=True)),
                (
                    "owner",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="services",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "category",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="services",
                        to="services.servicecategory",
                    ),
                ),
            ],
            options={
                "ordering": ["name"],
            },
            bases=(django_lifecycle.mixins.LifecycleModelMixin, models.Model),
        ),
        migrations.CreateModel(
            name="PremiumService",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created",
                    model_utils.fields.AutoCreatedField(
                        default=django.utils.timezone.now,
                        editable=False,
                        verbose_name="created",
                    ),
                ),
                (
                    "modified",
                    model_utils.fields.AutoLastModifiedField(
                        default=django.utils.timezone.now,
                        editable=False,
                        verbose_name="modified",
                    ),
                ),
                ("name", models.CharField(db_index=True, max_length=200)),
                ("slug", models.SlugField(blank=True, unique=True)),
                (
                    "service_type",
                    models.CharField(
                        choices=[
                            ("basic", "Basic Service"),
                            ("premium", "Premium Service"),
                            ("specialized", "Specialized Service"),
                        ],
                        default="basic",
                        max_length=20,
                    ),
                ),
                (
                    "short_desc",
                    models.CharField(
                        db_index=True,
                        max_length=300,
                        validators=[services.models.validate_base_service_short_desc],
                    ),
                ),
                (
                    "description",
                    models.TextField(
                        validators=[services.models.validate_base_service_description]
                    ),
                ),
                (
                    "base_price",
                    models.DecimalField(
                        db_index=True,
                        decimal_places=2,
                        max_digits=10,
                        validators=[utils.validation_utils.validate_positive_price],
                    ),
                ),
                ("is_active", models.BooleanField(db_index=True, default=True)),
                ("priority_support", models.BooleanField(default=False)),
                ("extended_warranty_months", models.IntegerField(default=0)),
                (
                    "category",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="%(class)s_services",
                        to="services.servicecategory",
                    ),
                ),
            ],
            options={
                "db_table": "services_premiumservice",
            },
            bases=(models.Model,),
        ),
        migrations.CreateModel(
            name="BasicService",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created",
                    model_utils.fields.AutoCreatedField(
                        default=django.utils.timezone.now,
                        editable=False,
                        verbose_name="created",
                    ),
                ),
                (
                    "modified",
                    model_utils.fields.AutoLastModifiedField(
                        default=django.utils.timezone.now,
                        editable=False,
                        verbose_name="modified",
                    ),
                ),
                ("name", models.CharField(db_index=True, max_length=200)),
                ("slug", models.SlugField(blank=True, unique=True)),
                (
                    "service_type",
                    models.CharField(
                        choices=[
                            ("basic", "Basic Service"),
                            ("premium", "Premium Service"),
                            ("specialized", "Specialized Service"),
                        ],
                        default="basic",
                        max_length=20,
                    ),
                ),
                (
                    "short_desc",
                    models.CharField(
                        db_index=True,
                        max_length=300,
                        validators=[services.models.validate_base_service_short_desc],
                    ),
                ),
                (
                    "description",
                    models.TextField(
                        validators=[services.models.validate_base_service_description]
                    ),
                ),
                (
                    "base_price",
                    models.DecimalField(
                        db_index=True,
                        decimal_places=2,
                        max_digits=10,
                        validators=[utils.validation_utils.validate_positive_price],
                    ),
                ),
                ("is_active", models.BooleanField(db_index=True, default=True)),
                (
                    "category",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="%(class)s_services",
                        to="services.servicecategory",
                    ),
                ),
            ],
            options={
                "db_table": "services_basicservice",
            },
            bases=(models.Model,),
        ),
        migrations.CreateModel(
            name="ServiceRatingAggregation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "average",
                    models.DecimalField(decimal_places=2, default=0, max_digits=3),
                ),
                ("count", models.PositiveIntegerField(default=0)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "service",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="rating_aggregation",
                        to="services.service",
                    ),
                ),
            ],
            options={
                "ordering": ["-updated_at"],
            },
        ),
        migrations.CreateModel(
            name="SpecializedService",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created",
                    model_utils.fields.AutoCreatedField(
                        default=django.utils.timezone.now,
                        editable=False,
                        verbose_name="created",
                    ),
                ),
                (
                    "modified",
                    model_utils.fields.AutoLastModifiedField(
                        default=django.utils.timezone.now,
                        editable=False,
                        verbose_name="modified",
                    ),
                ),
                ("name", models.CharField(db_index=True, max_length=200)),
                ("slug", models.SlugField(blank=True, unique=True)),
                (
                    "service_type",
                    models.CharField(
                        choices=[
                            ("basic", "Basic Service"),
                            ("premium", "Premium Service"),
                            ("specialized", "Specialized Service"),
                        ],
                        default="basic",
                        max_length=20,
                    ),
                ),
                (
                    "short_desc",
                    models.CharField(
                        db_index=True,
                        max_length=300,
                        validators=[services.models.validate_base_service_short_desc],
                    ),
                ),
                (
                    "description",
                    models.TextField(
                        validators=[services.models.validate_base_service_description]
                    ),
                ),
                (
                    "base_price",
                    models.DecimalField(
                        db_index=True,
                        decimal_places=2,
                        max_digits=10,
                        validators=[utils.validation_utils.validate_positive_price],
                    ),
                ),
                ("is_active", models.BooleanField(db_index=True, default=True)),
                (
                    "complexity_factor",
                    models.DecimalField(decimal_places=2, default=1.0, max_digits=3),
                ),
                (
                    "required_equipment_cost",
                    models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
                ),
                (
                    "category",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="%(class)s_services",
                        to="services.servicecategory",
                    ),
                ),
            ],
            options={
                "db_table": "services_specializedservice",
            },
            bases=(models.Model,),
        ),
        migrations.CreateModel(
            name="Review",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created",
                    model_utils.fields.AutoCreatedField(
                        default=django.utils.timezone.now,
                        editable=False,
                        verbose_name="created",
                    ),
                ),
                (
                    "modified",
                    model_utils.fields.AutoLastModifiedField(
                        default=django.utils.timezone.now,
                        editable=False,
                        verbose_name="modified",
                    ),
                ),
                (
                    "rating",
                    models.IntegerField(
                        db_index=True,
                        validators=[
                            django.core.validators.MinValueValidator(1),
                            django.core.validators.MaxValueValidator(5),
                        ],
                    ),
                ),
                ("text", models.TextField()),
                ("sentiment_polarity", models.FloatField(db_index=True, default=0.0)),
                ("sentiment_subjectivity", models.FloatField(default=0.0)),
                (
                    "sentiment_label",
                    models.CharField(db_index=True, default="neutral", max_length=20),
                ),
                ("is_flagged", models.BooleanField(db_index=True, default=False)),
                (
                    "flagged_reason",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "service",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="reviews",
                        to="services.service",
                    ),
                ),
            ],
            options={
                "ordering": ["-created", "-modified"],
                "abstract": False,
                "unique_together": {("service", "user")},
            },
        ),
        migrations.AddIndex(
            model_name="service",
            index=models.Index(
                fields=["category", "is_active"], name="services_se_categor_b50c86_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="service",
            index=models.Index(
                fields=["price", "is_active"], name="services_se_price_bc586b_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="service",
            index=models.Index(
                fields=["name", "category"], name="services_se_name_77ac23_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="service",
            index=models.Index(
                fields=["is_active", "created"], name="services_se_is_acti_e616c6_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="service",
            index=models.Index(
                fields=["price", "category", "is_active"],
                name="services_se_price_f1a9b3_idx",
            ),
        ),
    ]
