# Generated by Django 5.2.7 on 2025-10-15 12:05

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("services", "0004_add_owner_field_to_service"),
    ]

    operations = [
        migrations.AlterField(
            model_name="service",
            name="owner",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="services",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
