# Generated by Django 5.0 on 2025-09-26 03:26

from decimal import Decimal

import caching.base
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0001_initial"),
        ("contenttypes", "0002_remove_content_type_name"),
    ]

    operations = [
        migrations.CreateModel(
            name="BusinessCustomer",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "customer_type",
                    models.CharField(
                        choices=[
                            ("individual", "Individual Customer"),
                            ("business", "Business Customer"),
                            ("government", "Government Customer"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "email",
                    models.EmailField(db_index=True, max_length=254, unique=True),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True, db_index=True)),
                ("business_name", models.CharField(db_index=True, max_length=100)),
                ("tax_id", models.CharField(db_index=True, max_length=50, unique=True)),
                (
                    "business_size",
                    models.CharField(
                        choices=[
                            ("small", "Small"),
                            ("medium", "Medium"),
                            ("large", "Large"),
                        ],
                        max_length=20,
                    ),
                ),
                ("employee_count", models.PositiveIntegerField(default=1)),
                (
                    "annual_revenue",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=15, null=True,
                    ),
                ),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Business Customer",
                "verbose_name_plural": "Business Customers",
            },
            bases=(caching.base.CachingMixin, models.Model),
        ),
        migrations.CreateModel(
            name="CustomerBillingAddress",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("object_id", models.PositiveIntegerField()),
                ("address_line_1", models.CharField(max_length=255)),
                ("address_line_2", models.CharField(blank=True, max_length=255)),
                ("city", models.CharField(max_length=100)),
                ("state", models.CharField(max_length=100)),
                ("postal_code", models.CharField(max_length=20)),
                ("country", models.CharField(max_length=100)),
                ("is_default", models.BooleanField(default=False)),
                (
                    "content_type",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="contenttypes.contenttype",
                    ),
                ),
            ],
            options={
                "verbose_name": "Customer Billing Address",
                "verbose_name_plural": "Customer Billing Addresses",
            },
            bases=(caching.base.CachingMixin, models.Model),
        ),
        migrations.CreateModel(
            name="GovernmentCustomer",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "customer_type",
                    models.CharField(
                        choices=[
                            ("individual", "Individual Customer"),
                            ("business", "Business Customer"),
                            ("government", "Government Customer"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "email",
                    models.EmailField(db_index=True, max_length=254, unique=True),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True, db_index=True)),
                (
                    "government_entity_name",
                    models.CharField(db_index=True, max_length=150),
                ),
                (
                    "government_id",
                    models.CharField(db_index=True, max_length=50, unique=True),
                ),
                ("department", models.CharField(max_length=100)),
                ("contact_person", models.CharField(max_length=100)),
                (
                    "entity_type",
                    models.CharField(
                        choices=[
                            ("federal", "Federal"),
                            ("state", "State"),
                            ("local", "Local"),
                            ("other", "Other"),
                        ],
                        max_length=50,
                    ),
                ),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Government Customer",
                "verbose_name_plural": "Government Customers",
            },
            bases=(caching.base.CachingMixin, models.Model),
        ),
        migrations.CreateModel(
            name="IndividualCustomer",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "customer_type",
                    models.CharField(
                        choices=[
                            ("individual", "Individual Customer"),
                            ("business", "Business Customer"),
                            ("government", "Government Customer"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "email",
                    models.EmailField(db_index=True, max_length=254, unique=True),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True, db_index=True)),
                ("first_name", models.CharField(db_index=True, max_length=50)),
                ("last_name", models.CharField(max_length=50)),
                ("phone", models.CharField(blank=True, db_index=True, max_length=20)),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Individual Customer",
                "verbose_name_plural": "Individual Customers",
            },
            bases=(caching.base.CachingMixin, models.Model),
        ),
        migrations.CreateModel(
            name="CustomerServiceHistory",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("object_id", models.PositiveIntegerField()),
                ("service", models.CharField(db_index=True, max_length=200)),
                (
                    "service_date",
                    models.DateTimeField(auto_now_add=True, db_index=True),
                ),
                ("service_cost", models.DecimalField(decimal_places=2, max_digits=10)),
                (
                    "discount_applied",
                    models.DecimalField(
                        decimal_places=2, default=Decimal("0.00"), max_digits=5,
                    ),
                ),
                ("final_cost", models.DecimalField(decimal_places=2, max_digits=10)),
                (
                    "content_type",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="contenttypes.contenttype",
                    ),
                ),
            ],
            options={
                "verbose_name": "Customer Service History",
                "verbose_name_plural": "Customer Service Histories",
                "ordering": ["-service_date"],
                "indexes": [
                    models.Index(
                        fields=["content_type", "object_id"],
                        name="accounts_cu_content_a8f872_idx",
                    ),
                    models.Index(
                        fields=["service_date", "content_type", "object_id"],
                        name="accounts_cu_service_9ba9c7_idx",
                    ),
                ],
            },
            bases=(caching.base.CachingMixin, models.Model),
        ),
    ]
