# Generated by Django 5.0 on 2025-09-26 11:38

import django.utils.timezone
import model_utils.fields
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0002_businesscustomer_customerbillingaddress_and_more"),
        ("contenttypes", "0002_remove_content_type_name"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="customerservicehistory",
            options={
                "ordering": ["-created"],
                "verbose_name": "Customer Service History",
                "verbose_name_plural": "Customer Service Histories",
            },
        ),
        migrations.RemoveIndex(
            model_name="customerservicehistory",
            name="accounts_cu_service_9ba9c7_idx",
        ),
        migrations.RemoveField(
            model_name="businesscustomer",
            name="created_at",
        ),
        migrations.RemoveField(
            model_name="businesscustomer",
            name="updated_at",
        ),
        migrations.RemoveField(
            model_name="customerbillingaddress",
            name="created_at",
        ),
        migrations.RemoveField(
            model_name="customerbillingaddress",
            name="updated_at",
        ),
        migrations.RemoveField(
            model_name="customerservicehistory",
            name="created_at",
        ),
        migrations.RemoveField(
            model_name="customerservicehistory",
            name="service_date",
        ),
        migrations.RemoveField(
            model_name="customerservicehistory",
            name="updated_at",
        ),
        migrations.RemoveField(
            model_name="governmentcustomer",
            name="created_at",
        ),
        migrations.RemoveField(
            model_name="governmentcustomer",
            name="updated_at",
        ),
        migrations.RemoveField(
            model_name="individualcustomer",
            name="created_at",
        ),
        migrations.RemoveField(
            model_name="individualcustomer",
            name="updated_at",
        ),
        migrations.RemoveField(
            model_name="userprofile",
            name="created_at",
        ),
        migrations.RemoveField(
            model_name="userprofile",
            name="updated_at",
        ),
        migrations.AddField(
            model_name="customerbillingaddress",
            name="created",
            field=model_utils.fields.AutoCreatedField(
                default=django.utils.timezone.now,
                editable=False,
                verbose_name="created",
            ),
        ),
        migrations.AddField(
            model_name="customerbillingaddress",
            name="modified",
            field=model_utils.fields.AutoLastModifiedField(
                default=django.utils.timezone.now,
                editable=False,
                verbose_name="modified",
            ),
        ),
        migrations.AddField(
            model_name="customerservicehistory",
            name="created",
            field=model_utils.fields.AutoCreatedField(
                default=django.utils.timezone.now,
                editable=False,
                verbose_name="created",
            ),
        ),
        migrations.AddField(
            model_name="customerservicehistory",
            name="modified",
            field=model_utils.fields.AutoLastModifiedField(
                default=django.utils.timezone.now,
                editable=False,
                verbose_name="modified",
            ),
        ),
        migrations.AddField(
            model_name="userprofile",
            name="created",
            field=model_utils.fields.AutoCreatedField(
                default=django.utils.timezone.now,
                editable=False,
                verbose_name="created",
            ),
        ),
        migrations.AddField(
            model_name="userprofile",
            name="modified",
            field=model_utils.fields.AutoLastModifiedField(
                default=django.utils.timezone.now,
                editable=False,
                verbose_name="modified",
            ),
        ),
        migrations.AddIndex(
            model_name="customerservicehistory",
            index=models.Index(
                fields=["created", "content_type", "object_id"],
                name="accounts_cu_created_930c8f_idx",
            ),
        ),
    ]
