# Generated by Django 5.0 on 2025-09-23 09:33

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="EmailTracking",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "email_type",
                    models.CharField(
                        choices=[
                            ("welcome", "Welcome Email"),
                            ("order_confirmation", "Order Confirmation"),
                            ("payment_confirmation", "Payment Confirmation"),
                            ("review_notification", "Review Notification"),
                            ("password_reset", "Password Reset"),
                            ("account_verification", "Account Verification"),
                            ("other", "Other"),
                        ],
                        max_length=50,
                    ),
                ),
                ("recipient_email", models.EmailField(max_length=254)),
                ("subject", models.CharField(max_length=200)),
                ("sent_at", models.DateTimeField(auto_now_add=True)),
                ("delivered_at", models.DateTimeField(blank=True, null=True)),
                ("opened_at", models.DateTimeField(blank=True, null=True)),
                ("clicked_at", models.DateTimeField(blank=True, null=True)),
                ("is_opened", models.BooleanField(default=False)),
                ("is_clicked", models.BooleanField(default=False)),
                ("error_message", models.TextField(blank=True, null=True)),
            ],
            options={
                "verbose_name": "Email Tracking",
                "verbose_name_plural": "Email Tracking",
                "db_table": "email_tracking",
            },
        ),
        migrations.CreateModel(
            name="EmailQueue",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("email_type", models.CharField(max_length=50)),
                ("subject", models.CharField(max_length=200)),
                ("template_name", models.CharField(max_length=100)),
                ("context_data", models.TextField()),
                ("recipient_list", models.TextField()),
                (
                    "from_email",
                    models.EmailField(blank=True, max_length=254, null=True),
                ),
                ("attachments", models.TextField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("scheduled_at", models.DateTimeField()),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("processing", "Processing"),
                            ("sent", "Sent"),
                            ("failed", "Failed"),
                        ],
                        default="pending",
                        max_length=20,
                    ),
                ),
                ("retry_count", models.IntegerField(default=0)),
                ("max_retries", models.IntegerField(default=3)),
                ("error_message", models.TextField(blank=True, null=True)),
            ],
            options={
                "verbose_name": "Email Queue",
                "verbose_name_plural": "Email Queue",
                "db_table": "email_queue",
                "indexes": [
                    models.Index(
                        fields=["status", "scheduled_at"],
                        name="email_queue_status_e1d260_idx",
                    ),
                ],
            },
        ),
        migrations.CreateModel(
            name="PopularSearch",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("query", models.CharField(db_index=True, max_length=255)),
                (
                    "language",
                    models.CharField(db_index=True, default="en", max_length=10),
                ),
                ("search_count", models.IntegerField(default=1)),
                (
                    "last_searched",
                    models.DateTimeField(
                        db_index=True,
                        default=django.utils.timezone.now,
                    ),
                ),
            ],
            options={
                "ordering": ["-search_count"],
                "indexes": [
                    models.Index(
                        fields=["query", "language"],
                        name="utils_popul_query_42b877_idx",
                    ),
                    models.Index(
                        fields=["search_count"],
                        name="utils_popul_search__f8c2f0_idx",
                    ),
                    models.Index(
                        fields=["last_searched"],
                        name="utils_popul_last_se_3c736a_idx",
                    ),
                ],
                "unique_together": {("query", "language")},
            },
        ),
        migrations.CreateModel(
            name="SearchAnalytics",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("query", models.CharField(db_index=True, max_length=255)),
                (
                    "language",
                    models.CharField(db_index=True, default="en", max_length=10),
                ),
                ("results_count", models.IntegerField(default=0)),
                (
                    "created_at",
                    models.DateTimeField(
                        db_index=True,
                        default=django.utils.timezone.now,
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["query", "language"],
                        name="utils_searc_query_510ed7_idx",
                    ),
                    models.Index(
                        fields=["created_at", "language"],
                        name="utils_searc_created_6b77db_idx",
                    ),
                ],
            },
        ),
    ]
