# Generated by Django 5.0 on 2025-09-26 11:38

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("utils", "0001_initial"),
    ]

    operations = [
        migrations.DeleteModel(
            name="EmailQueue",
        ),
        migrations.DeleteModel(
            name="EmailTracking",
        ),
    ]
