# Generated by Django 5.2.7 on 2025-10-23 10:06

from decimal import Decimal

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
import django_fsm
import model_utils.fields
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("services", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Order",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created",
                    model_utils.fields.AutoCreatedField(
                        default=django.utils.timezone.now,
                        editable=False,
                        verbose_name="created",
                    ),
                ),
                (
                    "modified",
                    model_utils.fields.AutoLastModifiedField(
                        default=django.utils.timezone.now,
                        editable=False,
                        verbose_name="modified",
                    ),
                ),
                (
                    "_status",
                    django_fsm.FSMField(
                        choices=[
                            ("draft", "Draft"),
                            ("pending", "Pending"),
                            ("confirmed", "Confirmed"),
                            ("processing", "Processing"),
                            ("shipped", "Shipped"),
                            ("delivered", "Delivered"),
                            ("completed", "Completed"),
                            ("cancelled", "Cancelled"),
                            ("refunded", "Refunded"),
                            ("on_hold", "On Hold"),
                            ("disputed", "Disputed"),
                        ],
                        db_column="status",
                        db_index=True,
                        default="draft",
                        max_length=50,
                    ),
                ),
                (
                    "_payment_status",
                    django_fsm.FSMField(
                        choices=[
                            ("unpaid", "Unpaid"),
                            ("pending", "Pending"),
                            ("paid", "Paid"),
                            ("partially_refuned", "Partially Refuned"),
                            ("refunded", "Refunded"),
                            ("failed", "Failed"),
                            ("disputed", "Disputed"),
                        ],
                        db_column="payment_status",
                        db_index=True,
                        default="unpaid",
                        max_length=50,
                        protected=True,
                    ),
                ),
                ("customer_name", models.CharField(max_length=100)),
                ("customer_address", models.TextField()),
                ("customer_phone", models.CharField(blank=True, max_length=20)),
                (
                    "_subtotal",
                    models.DecimalField(
                        db_column="subtotal",
                        decimal_places=2,
                        default=Decimal("0.00"),
                        max_digits=10,
                    ),
                ),
                (
                    "_tax",
                    models.DecimalField(
                        db_column="tax",
                        decimal_places=2,
                        default=Decimal("0.00"),
                        max_digits=10,
                    ),
                ),
                (
                    "_total",
                    models.DecimalField(
                        db_column="total",
                        decimal_places=2,
                        default=Decimal("0.00"),
                        max_digits=10,
                    ),
                ),
                (
                    "order_id",
                    models.CharField(db_index=True, max_length=50, unique=True),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="orders",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="ExpressOrder",
            fields=[
                (
                    "order_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="orders.order",
                    ),
                ),
                (
                    "express_fee",
                    models.DecimalField(
                        decimal_places=2, default=Decimal("100.00"), max_digits=10
                    ),
                ),
            ],
            options={
                "verbose_name": "Express Order",
                "verbose_name_plural": "Express Orders",
            },
            bases=("orders.order",),
        ),
        migrations.CreateModel(
            name="ScheduledOrder",
            fields=[
                (
                    "order_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="orders.order",
                    ),
                ),
                ("scheduled_date", models.DateTimeField()),
                ("reminder_sent", models.BooleanField(default=False)),
            ],
            options={
                "verbose_name": "Scheduled Order",
                "verbose_name_plural": "Scheduled Orders",
            },
            bases=("orders.order",),
        ),
        migrations.CreateModel(
            name="StandardOrder",
            fields=[],
            options={
                "proxy": True,
                "indexes": [],
                "constraints": [],
            },
            bases=("orders.order",),
        ),
        migrations.CreateModel(
            name="OrderItem",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "quantity",
                    models.PositiveIntegerField(
                        validators=[django.core.validators.MinValueValidator(1)]
                    ),
                ),
                ("unit_price", models.DecimalField(decimal_places=2, max_digits=10)),
                (
                    "price",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=10, null=True
                    ),
                ),
                (
                    "order",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="items",
                        to="orders.order",
                    ),
                ),
                (
                    "service",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="services.service",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.AddIndex(
            model_name="order",
            index=models.Index(
                fields=["user", "_status"], name="orders_orde_user_id_02a211_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="order",
            index=models.Index(
                fields=["_status", "created"], name="orders_orde_status_5a4cbe_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="order",
            index=models.Index(
                fields=["_payment_status", "_status"],
                name="orders_orde_payment_3f48de_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="order",
            index=models.Index(
                fields=["created"], name="orders_orde_created_51311f_idx"
            ),
        ),
        migrations.AddConstraint(
            model_name="order",
            constraint=models.UniqueConstraint(
                condition=models.Q(("_status", "draft")),
                fields=("user", "_status"),
                name="unique_draft_order_per_user",
            ),
        ),
    ]
