# Generated by Django 5.0 on 2025-09-26 03:24

from decimal import Decimal

import django.db.models.deletion
import django_fsm
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("orders", "0003_make_price_nullable"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="ExpressOrder",
            fields=[
                (
                    "order_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="orders.order",
                    ),
                ),
                (
                    "express_fee",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("100.00"),
                        max_digits=10,
                    ),
                ),
            ],
            options={
                "verbose_name": "Express Order",
                "verbose_name_plural": "Express Orders",
            },
            bases=("orders.order",),
        ),
        migrations.CreateModel(
            name="ScheduledOrder",
            fields=[
                (
                    "order_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="orders.order",
                    ),
                ),
                ("scheduled_date", models.DateTimeField()),
                ("reminder_sent", models.BooleanField(default=False)),
            ],
            options={
                "verbose_name": "Scheduled Order",
                "verbose_name_plural": "Scheduled Orders",
            },
            bases=("orders.order",),
        ),
        migrations.CreateModel(
            name="StandardOrder",
            fields=[],
            options={
                "proxy": True,
                "indexes": [],
                "constraints": [],
            },
            bases=("orders.order",),
        ),
        migrations.AlterModelOptions(
            name="order",
            options={},
        ),
        migrations.RemoveIndex(
            model_name="order",
            name="orders_orde_user_id_02a211_idx",
        ),
        migrations.RemoveIndex(
            model_name="order",
            name="orders_orde_status_25e057_idx",
        ),
        migrations.RemoveIndex(
            model_name="order",
            name="orders_orde_payment_bc131d_idx",
        ),
        migrations.RemoveIndex(
            model_name="order",
            name="orders_orde_order_i_205064_idx",
        ),
        migrations.RemoveField(
            model_name="order",
            name="payment_status",
        ),
        migrations.RemoveField(
            model_name="order",
            name="status",
        ),
        migrations.RemoveField(
            model_name="order",
            name="subtotal",
        ),
        migrations.RemoveField(
            model_name="order",
            name="tax",
        ),
        migrations.RemoveField(
            model_name="order",
            name="total",
        ),
        migrations.AddField(
            model_name="order",
            name="_payment_status",
            field=django_fsm.FSMField(
                choices=[
                    ("unpaid", "Unpaid"),
                    ("pending", "Pending"),
                    ("paid", "Paid"),
                    ("partially_refunded", "Partially Refunded"),
                    ("refunded", "Refunded"),
                    ("failed", "Failed"),
                    ("disputed", "Disputed"),
                ],
                db_column="payment_status",
                db_index=True,
                default="unpaid",
                max_length=50,
                protected=True,
            ),
        ),
        migrations.AddField(
            model_name="order",
            name="_status",
            field=django_fsm.FSMField(
                choices=[
                    ("draft", "Draft"),
                    ("pending", "Pending"),
                    ("confirmed", "Confirmed"),
                    ("processing", "Processing"),
                    ("shipped", "Shipped"),
                    ("delivered", "Delivered"),
                    ("completed", "Completed"),
                    ("cancelled", "Cancelled"),
                    ("refunded", "Refunded"),
                    ("on_hold", "On Hold"),
                    ("disputed", "Disputed"),
                ],
                db_column="status",
                db_index=True,
                default="draft",
                max_length=50,
            ),
        ),
        migrations.AddField(
            model_name="order",
            name="_subtotal",
            field=models.DecimalField(
                db_column="subtotal",
                decimal_places=2,
                default=Decimal("0.00"),
                max_digits=10,
            ),
        ),
        migrations.AddField(
            model_name="order",
            name="_tax",
            field=models.DecimalField(
                db_column="tax",
                decimal_places=2,
                default=Decimal("0.00"),
                max_digits=10,
            ),
        ),
        migrations.AddField(
            model_name="order",
            name="_total",
            field=models.DecimalField(
                db_column="total",
                decimal_places=2,
                default=Decimal("0.00"),
                max_digits=10,
            ),
        ),
        migrations.AddIndex(
            model_name="order",
            index=models.Index(
                fields=["user", "_status"],
                name="orders_orde_user_id_02a211_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="order",
            index=models.Index(
                fields=["_status", "created_at"],
                name="orders_orde_status_25e057_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="order",
            index=models.Index(
                fields=["_payment_status", "_status"],
                name="orders_orde_payment_3f48de_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="order",
            index=models.Index(
                fields=["created_at"],
                name="orders_orde_created_0e92de_idx",
            ),
        ),
    ]
