# Generated by Django 5.0 on 2025-09-26 11:38

import django.utils.timezone
import django_fsm
import model_utils.fields
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("orders", "0004_expressorder_scheduledorder_standardorder_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name="order",
            name="orders_orde_status_25e057_idx",
        ),
        migrations.RemoveIndex(
            model_name="order",
            name="orders_orde_created_0e92de_idx",
        ),
        migrations.RemoveField(
            model_name="order",
            name="created_at",
        ),
        migrations.RemoveField(
            model_name="order",
            name="updated_at",
        ),
        migrations.AddField(
            model_name="order",
            name="created",
            field=model_utils.fields.AutoCreatedField(
                default=django.utils.timezone.now,
                editable=False,
                verbose_name="created",
            ),
        ),
        migrations.AddField(
            model_name="order",
            name="modified",
            field=model_utils.fields.AutoLastModifiedField(
                default=django.utils.timezone.now,
                editable=False,
                verbose_name="modified",
            ),
        ),
        migrations.AlterField(
            model_name="order",
            name="_payment_status",
            field=django_fsm.FSMField(
                choices=[
                    ("unpaid", "Unpaid"),
                    ("pending", "Pending"),
                    ("paid", "Paid"),
                    ("partially_refuned", "Partially Refuned"),
                    ("refunded", "Refunded"),
                    ("failed", "Failed"),
                    ("disputed", "Disputed"),
                ],
                db_column="payment_status",
                db_index=True,
                default="unpaid",
                max_length=50,
                protected=True,
            ),
        ),
        migrations.AddIndex(
            model_name="order",
            index=models.Index(
                fields=["_status", "created"], name="orders_orde_status_5a4cbe_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="order",
            index=models.Index(
                fields=["created"], name="orders_orde_created_51311f_idx",
            ),
        ),
    ]
